// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeStatsForVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeStatsForVS.f532d7a0-94db-4494-9a22-b29b8c9c0a62";
        public const string Name = "CodeStatsForVS";
        public const string Description = @"A Visual Studio Plugin for CodeStats..";
        public const string Language = "ru-RU";
        public const string Version = "1.0";
        public const string Author = "Andrey Belov";
        public const string Tags = "code, tracking, statistics, analytics";
    }
}
