// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeStatsForVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeStatsForVS.f532d7a0-94db-4494-9a22-b29b8c9c0a62";
        public const string Name = "CodeStats (For VS2022)";
        public const string Description = @"A Visual Studio 2022 Plugin for CodeStats.";
        public const string Language = "ru-RU";
        public const string Version = "1.3";
        public const string Author = "Andrey Belov";
        public const string Tags = "code, tracking, statistics, analytics";
    }
}
