// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

namespace CodeStatsForVS
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        /// <summary>
        /// String GUID for CodeStats Package.
        /// </summary>
        public const string CodeStatsForVSString = "94c71949-dcde-4862-9daf-287908ee04fa";

        /// <summary>
        /// GUID for CodeStats Package.
        /// </summary>
        public static Guid VCodeStatsForVS = new Guid(CodeStatsForVSString);

        /// <summary>
        /// String GUID for Stats Window.
        /// </summary>
        public const string StatsWindowString = "D5489F06-DF12-4987-8127-C4467BBA684B";

        /// <summary>
        /// GUID for Stats Window.
        /// </summary>
        public static Guid StatsWindow = new Guid(StatsWindowString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        /// <summary>
        /// CommandId for ShadowStats Command.
        /// </summary>
        public const int ShowStats = 0x0100;

        /// <summary>
        /// CommandId for Stats Window.
        /// </summary>
        public const int StatsWindow = 0x0BB8;
    }
}